/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ar.com.grupoesfera.capacitacion.enviospostales;

import org.junit.Test;
import static org.junit.Assert.*;

public class AplicacionTest {

    @Test
    public void laAplicacionDeberiaMostrarElMensajeDeBienvenida() {
        Aplicacion classUnderTest = new Aplicacion();
        assertNotNull("Debería mostrar el mensaje de bienvenida", classUnderTest.getGreeting());
    }
}
