/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ar.com.grupoesfera.capacitacion.enviospostales;

public class Aplicacion {
    public String getGreeting() {
        return "Hola Curso de Integración Continua!.";
    }

    public static void main(String[] args) {
        System.out.println(new Aplicacion().getGreeting());
    }
}
